---
# The following packages are "basic packages" that I think a system should have installed
- name: Install some basic packages
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
   - socat
   - htop
   - iotop
   - vim
   - git
   - rsync
