---
# The following packages are "basic packages" that I think a system should have installed
- name: Install some basic packages
  action: "{{ ansible_pkg_mgr }}"
  args:
    name:
     - socat
     - htop
     - iotop
     - vim
     - git
     - rsync
    state: latest
