---
- name: Init the has_rpm fact
  set_fact:
    has_rpm: false

- name: Init the has_firewalld fact
  set_fact:
    has_firewalld: false

- name: Determine if has rpm
  stat:
    path: /usr/bin/rpm
  register: s
  changed_when: false
  always_run: yes

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: s.stat.exists

- name: RPM | Determine if firewalld installed
  command: "rpm -q firewalld"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes
  when: has_rpm

- name: Set the has_firewalld fact
  set_fact:
    has_firewalld: true
  when: has_rpm and s.rc is defined and s.rc == 0

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: has_firewalld
