---
- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: has_firewalld

- name: Remove firewalld service
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: firewalld
    state: absent
  when: has_firewalld
