---
- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: has_firewalld

- name: Install iptables-persistent
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "iptables-services"
    state: latest
