---
- name: Get current hostname
  shell: "hostnamectl || hostname"
  register: hostname_out

- name: Set Inventory Name as Hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }} || hostname {{ inventory_hostname }}"
  when: "'{{ inventory_hostname }}' not in hostname_out.stdout"
