---
- include: wall.yml

# Set hostname to inventory_hostname
- include: hostname.yml

# Generate custom motd file
- include: motd.yml

# Generate /etc/hosts file
- include: hosts.yml

- include: upgrade.yml

- include: fedora-install.yml
  when: not is_atomic and ansible_distribution == "Fedora"
