---
- ansible.builtin.include_tasks:
    file: wall.yml

# Set hostname to inventory_hostname
- ansible.builtin.include_tasks:
    file: hostname.yml

# Generate custom motd file
- ansible.builtin.include_tasks:
    file: motd.yml

# Generate /etc/hosts file
- ansible.builtin.include_tasks:
    file: hosts.yml

- ansible.builtin.include_tasks:
    file: basic_packages.yml

- ansible.builtin.include_tasks:
    file: fedora-install.yml
  when: (is_atomic is defined or not is_atomic) and ansible_distribution == "Fedora"
