---
- include_tasks: wall.yml

# Set hostname to inventory_hostname
- include_tasks: hostname.yml

# Generate custom motd file
- include_tasks: motd.yml

# Generate /etc/hosts file
- include_tasks: hosts.yml

- include_tasks: basic_packages.yml

- include_tasks: fedora-install.yml
  when: (is_atomic is defined or not is_atomic) and ansible_distribution == "Fedora"
