---
- fail:
    msg: "Invalid Ansible apt upgrade mode given."
  when: upgrade_mode is defined and (upgrade_mode != "no" and upgrade_mode != "yes" and upgrade_mode != "safe" and upgrade_mode != "full" and upgrade_mode != "dist")

# The following packages are "basic packages" that I think a system should have installed
- name: Install some basic packages
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: installed
  with_items:
   - socat
   - htop
   - iotop
   - vim
   - git
   - rsync
