---
- name: Send out ansible deployment started broadcast message
  shell: |
    echo '+-------------------------------------------+
    | =>   ANSIBLE DEPLOYMENT HAS STARTED!   <= |
    +===========================================+
    | Please close all connections if possible! |
    +-------------------------------------------+' | wall
  ignore_errors: true
